### ISSUE TITLE
Auth Fails with non-opendirectory bindings

### ISSUE THREAD

**Issue by ecrist** [joshua-d-miller/LAPS-for-macOS#6]
We use BeyondTrust's AD Bridge (f.k.a. PBIS) to bind our Macs to Active Directory.  When attempting to look up LAPS passwords for our Windows inventory, I'm just given a generic message, "Unable to retrieve computer record."

I'm guessing there are some dependencies or assumptions as to how a macOS device normally binds to AD using Apple's built-in tools.  I'm willing to help get this working in our environment and push this out on the AppStore (free) so that auto-update mechanisms in the AppStore can be leveraged with MDM solutions.

**Comment by joshua-d-miller** [comment]
@ecrist It sounds like BeyondTrust uses its own methodology to connect to AD whereas this product uses Apple's Open Directory Framework to connect to AD with the built-in tools. You would need to find out how BeyondTrust connects to AD and then see if that is something that they would allow in an open-source project and to then see if it can be used in Swift.

**Comment by astrugatch** [comment]
Having a similar issue with NoMAD. I can authenticate to domain resources without being bound but the tool seems unable to use this authentication method. 

Would it be possible to add a manual option to query the domain directly from the utility rather than utilizing the machine's binding?

**Comment by ecrist** [comment]
BeyondTrust has an open source version of their tools, so there shouldn't be any licensing conflicts.  What do you need from me to get this moving forward?

See here: https://github.com/BeyondTrust/pbis-open/wiki

**Comment by joshua-d-miller** [comment]
Hello @ecrist!

I'm incredibly sorry for the lack of response here. I know this issue has been open for a long time. Since BeyondTrust is a bit out of scope for this and something I'm not sure I can even implement I'm going to close this issue. I can however tell you that with the release of macOSLAPS 2.0.0, the password can be extracted and sent to "insert MDM here" which might be a better solution than using a 3rd party AD. If you'd like please join us on the MacAdmins Slack: https://macadmins.org in the channel `#macoslaps` and we can assist you further.

Thanks!
